version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile-test
    hostname: api
    command: ["npm", "run", "test"]
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "23088:8081"
    env_file:
      - docker/variables-test.env
    networks:
      - geocode
networks:
  default:
    driver: bridge
  geocode:
    driver: bridge
