version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: api
    command: ["npm", "run", "start"]
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - docker/variables.env
networks:
  default:
    driver: bridge
