version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-import:/var/lib/postgresql/import
    env_file:
      - ./variables.env
    ports:
      - "127.0.0.1:15435:5432"
    networks:
      - owner_api
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    hostname: api
    command: bash -c "./wait-for-it/wait-for-it.sh postgres:5432 -t 300 && npx sequelize db:migrate && npm run start"
    volumes:
      - ../:/usr/src/api
      - ../node_modules:/usr/src/api/node_modules
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./variables.env
    networks:
      - owner_api
networks:
  default:
    driver: bridge
  owner_api:
    driver: bridge
