version: '3'
services:
  owner_postgres:
    image: postgres:10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-import:/var/lib/postgresql/import
    env_file:
      - ./variables-local.env
    ports:
      - "15435:5432"
    networks:
      - owner_api
  owner_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile-local
    hostname: api
    # command: ["npm", "run", "start"]
    command: bash -c "./wait-for-it/wait-for-it.sh owner_postgres:5432 -t 300 && npx sequelize db:migrate && npm run dev"
    # command: ["npm", "run", "test"]
    # command: ["npm", "run", "hold"]
    volumes:
      - ../:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "23088:8081"
    env_file:
      - ./variables-local.env
    networks:
      - owner_api
    depends_on:
      - owner_postgres
networks:
  default:
    driver: bridge
  owner_api:
    driver: bridge
