const TermsToAbbr = {
  // Street Types
  'AVENUE': 'AVE',
  'ROAD': 'RD',
  'COURT': 'CT',
  'STREET': 'ST',
  'DRIVE': 'DR',
  'LANE': 'LN',
  'CIRCLE': 'CIR',
  'BOULEVARD': 'BLVD',
  'PIKE': 'PIKE',
  'EXTENSION': 'EXT',
  'PLACE': 'PL',
  'HIGHWAY': 'HWY',
  'TERRACE': 'TER',
  'WAY': 'WAY',
  'SQUARE': 'SQ',
  'ALLEY': 'ALY',
  'POINT': 'PT',
  'GREEN': 'GRN',
  'RUN': 'RUN',
  'TRAIL': 'TRL',
  'CENTER': 'CTR',
  'PATH': 'PATH',
  'WALK': 'WALK',
  'VIEW': 'VW',
  'STRAND': 'STRN',
  'RIDGE': 'RDG',
  'VILLAGE': 'VLG',
  'HARBOR': 'HBR',
  'PLAZA': 'PLZ',
  'CROSSING': 'XING',
  'PARK': 'PARK',
  'HEIGHTS': 'HTS',
  'MANOR': 'MNR',
  'TRACE': 'TRCE',
  'HILL': 'HL',
  'ROADWAY': 'RDWY',
  'SPUR': 'SPUR',
  'KNOLL': 'KNL',
  'PARKWAY': 'PKWY',
  'CRESCENT': 'CRES',
  'ROW': 'ROW',
  'OVAL': 'OVAL',
  'COMMONS': 'CMNS',
  'ESTATES': 'ESTS',
  'MALL': 'MALL',
  'END': 'END',
  'FIELD': 'FLD', // ? COULD NOT ACTUALLY CONFIRM AN ADDRESS WITH THIS
  'MEWS': 'MEWS',
  'EXPRESSWAY': 'EXPY',
  'ISLAND': 'IS',
  'TUNNEL': 'TUNL',
  // Cardinal Directions
  'NORTH': 'N',
  'SOUTH': 'S',
  'EAST': 'E',
  'WEST': 'W',
};

const OrdinalToNumWithSuffix = {
  'FIRST': '1ST',
  'SECOND': '2ND',
  'THIRD': '3RD',
  'FOURTH': '4TH',
  'FIFTH': '5TH',
  'SIXTH': '6TH',
  'SEVENTH': '7TH',
  'EIGHTH': '8TH',
  'NINTH': '9TH',
  'TENTH': '10TH',
  'ELEVENTH': '11TH',
  'TWELFTH': '12TH',
  'THIRTEENTH': '13TH',
  'FOURTEENTH': '14TH',
  'FIFTEENTH': '15TH',
  'SIXTEENTH': '16TH',
  'SEVENTEENTH': '17TH',
  'EIGHTEENTH': '18TH',
  'NINETEENTH': '19TH',
  'TWENTIETH': '20TH',
}

const AbbrToTerms = {
  // Street Types
  'AVE': 'AVENUE',
  'RD': 'ROAD',
  'CT': 'COURT',
  'ST': 'STREET',
  'DR': 'DRIVE',
  'LN': 'LANE',
  'CIR': 'CIRCLE',
  'BLVD': 'BOULEVARD',
  'PIKE': 'PIKE',
  'EXT': 'EXTENSION',
  'PL': 'PLACE',
  'HWY': 'HIGHWAY',
  'TER': 'TERRACE',
  'WAY': 'WAY',
  'SQ': 'SQUARE',
  'ALY': 'ALLEY',
  'PT': 'POINT',
  'GRN': 'GREEN',
  'RUN': 'RUN',
  'TRL': 'TRAIL',
  'CTR': 'CENTER',
  'PATH': 'PATH',
  'WALK': 'WALK',
  'VW': 'VIEW',
  'STRN': 'STRAND',
  'RDG': 'RIDGE',
  'VLG': 'VILLAGE',
  'HBR': 'HARBOR',
  'PLZ': 'PLAZA',
  'XING': 'CROSSING',
  'PARK': 'PARK',
  'HTS': 'HEIGHTS',
  'MNR': 'MANOR',
  'TRCE': 'TRACE',
  'HL': 'HILL',
  'RDWY': 'ROADWAY',
  'SPUR': 'SPUR',
  'KNL': 'KNOLL',
  'PKWY': 'PARKWAY',
  'CRES': 'CRESCENT',
  'ROW': 'ROW',
  'OVAL': 'OVAL',
  'CMNS': 'COMMONS',
  'ESTS': 'ESTATES',
  'MALL': 'MALL',
  'END': 'END',
  'FLD': 'FIELD', // ? COULD NOT ACTUALLY CONFIRM AN ADDRESS WITH THIS
  'MEWS': 'MEWS',
  'EXPY': 'EXPRESSWAY',
  'IS': 'ISLAND',
  'TUNL': 'TUNNEL',
  // Cardinal Directions
  'N': 'NORTH',
  'S': 'SOUTH',
  'E': 'EAST',
  'W': 'WEST',
  // Municipality alternatives
  // 'PITTSBURGH': 'PGH',
  'BORO': 'BOROUGH'
};

module.exports = {
  TERMS: TermsToAbbr,
  ABBRS: AbbrToTerms,
  ORDS: OrdinalToNumWithSuffix,
};
